# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (26 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/wesserboy/Overlays-MC-/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="wesserboysoverlays" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0.0.1" #mandatory

 # A display name for the mod
displayName="Wesserboy's Overlays" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/wesserboys-overlays" #optional

# A text field displayed in the mod UI
authors="Wesserboy" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Adds some helpful overlays to the game.
'''